<?php
	//includes
	include_once('../templates/tpl_common.php');
	include_once('../templates/tpl_admin.php');
	//page
	drawHead();
	drawHeaderAdmin(0);
    drawAdminStart(7);
    drawAdminInterface(1);
    drawAdminTable(7);
    drawAdminEnd();
	drawAdminFooter(); 
?>