<?php
	//includes
	include_once('../templates/tpl_common.php');
	include_once('../templates/tpl_product.php');
	//page
	drawHead(['activate_popovers.js']);
	drawHeader(0);
	drawProduct();
	drawFooter();
?>