INSERT INTO public.feedback (id, evaluation, comment, evaluation_date, user_id, key_id) VALUES (1, true, 'Great product. Thank you!', '2020-06-04', 7, 1);
INSERT INTO public.feedback (id, evaluation, comment, evaluation_date, user_id, key_id) VALUES (2, true, 'i''VS ENJOYED VERY MUCH THIS GAME!!!', '2020-06-04', 7, 2);
INSERT INTO public.feedback (id, evaluation, comment, evaluation_date, user_id, key_id) VALUES (3, false, 'the game is very slow and the seller didn''t fix it', '2020-06-04', 7, 3);
INSERT INTO public.feedback (id, evaluation, comment, evaluation_date, user_id, key_id) VALUES (4, true, 'Liked this game!!!!!!!', '2020-06-05', 3, 85);
INSERT INTO public.feedback (id, evaluation, comment, evaluation_date, user_id, key_id) VALUES (6, false, 'Best game ever', '2020-06-05', 3, 92);
INSERT INTO public.feedback (id, evaluation, comment, evaluation_date, user_id, key_id) VALUES (9, false, 'Awful game, same as last year, not worth a  buy', '2020-06-05', 3, 87);
INSERT INTO public.feedback (id, evaluation, comment, evaluation_date, user_id, key_id) VALUES (12, true, 'Great product', '2020-06-05', 7, 93);
INSERT INTO public.feedback (id, evaluation, comment, evaluation_date, user_id, key_id) VALUES (14, true, 'Best game ever', '2020-06-05', 7, 86);
INSERT INTO public.feedback (id, evaluation, comment, evaluation_date, user_id, key_id) VALUES (17, true, 'Really good, looks just like America in the current time. Thumbs up for realism', '2020-06-05', 7, 82);
INSERT INTO public.feedback (id, evaluation, comment, evaluation_date, user_id, key_id) VALUES (18, false, 'The seller sold be a key that didn''t workt.', '2020-06-05', 6, 88);
INSERT INTO public.feedback (id, evaluation, comment, evaluation_date, user_id, key_id) VALUES (20, true, 'Loved the game, no problems', '2020-06-05', 6, 83);
INSERT INTO public.feedback (id, evaluation, comment, evaluation_date, user_id, key_id) VALUES (23, true, 'No problem with the key, good customer support', '2020-06-05', 6, 94);
INSERT INTO public.feedback (id, evaluation, comment, evaluation_date, user_id, key_id) VALUES (27, true, 'The key had a problem but the seller was nice enough to give me another', '2020-06-05', 6, 95);