INSERT INTO feedback (evaluation, comment, evaluation_date, user_id, key_id) VALUES ( true, 'Great product. Thank you!', '2020-06-04', 7, 1);
INSERT INTO feedback (evaluation, comment, evaluation_date, user_id, key_id) VALUES ( true, 'i''VS ENJOYED VERY MUCH THIS GAME!!!', '2020-06-04', 7, 2);
INSERT INTO feedback (evaluation, comment, evaluation_date, user_id, key_id) VALUES ( false, 'the game is very slow and the seller didn''t fix it', '2020-06-04', 7, 3);
INSERT INTO feedback (evaluation, comment, evaluation_date, user_id, key_id) VALUES ( true, 'Liked this game!!!!!!!', '2020-06-05', 3, 85);
INSERT INTO feedback (evaluation, comment, evaluation_date, user_id, key_id) VALUES ( false, 'Best game ever', '2020-06-05', 3, 92);
INSERT INTO feedback (evaluation, comment, evaluation_date, user_id, key_id) VALUES ( false, 'Awful game, same as last year, not worth a  buy', '2020-06-05', 3, 87);
INSERT INTO feedback (evaluation, comment, evaluation_date, user_id, key_id) VALUES (true, 'Great product', '2020-06-05', 7, 93);
INSERT INTO feedback (evaluation, comment, evaluation_date, user_id, key_id) VALUES (true, 'Best game ever', '2020-06-05', 7, 86);
INSERT INTO feedback (evaluation, comment, evaluation_date, user_id, key_id) VALUES (true, 'Really good, looks just like America in the current time. Thumbs up for realism', '2020-06-05', 7, 82);
INSERT INTO feedback (evaluation, comment, evaluation_date, user_id, key_id) VALUES (false, 'The seller sold be a key that didn''t workt.', '2020-06-05', 6, 88);
INSERT INTO feedback (evaluation, comment, evaluation_date, user_id, key_id) VALUES (true, 'Loved the game, no problems', '2020-06-05', 6, 83);
INSERT INTO feedback (evaluation, comment, evaluation_date, user_id, key_id) VALUES (true, 'No problem with the key, good customer support', '2020-06-05', 6, 94);
INSERT INTO feedback (evaluation, comment, evaluation_date, user_id, key_id) VALUES (true, 'The key had a problem but the seller was nice enough to give me another', '2020-06-05', 6, 95);